services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: sh -c "python manage.py collectstatic --noinput && uvicorn tickr.asgi:application --host 0.0.0.0 --port 8000 --reload"
