# Generated by Django 6.0.2 on 2026-02-17 09:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_user_last_login'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_performed', to='accounts.user')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
    ]
